apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  meshConfig:
    trustDomain: example.org
    trustDomainAliases:
      - cluster.local
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network2
